  # To start:
  # docker-compose up -d
  # To stop:
  # docker-compose down
  # docker-compose exec postgres psql -U admin -d kiyoshi_db

services:
  postgres:
    image: postgres:16
    container_name: kiyoshi-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: kiyoshi_db
      # POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./seed_data.sql:/docker-entrypoint-initdb.d/02-seed_data.sql
      - ./procedures.sql/users.sql:/docker-entrypoint-initdb.d/03-users.sql
      - ./procedures.sql/employees.sql:/docker-entrypoint-initdb.d/04-employees.sql
      - ./procedures.sql/suppliers.sql:/docker-entrypoint-initdb.d/05-suppliers.sql
      - ./procedures.sql/inventory.sql:/docker-entrypoint-initdb.d/06-inventory.sql
      - ./procedures.sql/menu_items.sql:/docker-entrypoint-initdb.d/07-menu_items.sql
      - ./procedures.sql/orders.sql:/docker-entrypoint-initdb.d/08-orders.sql
      - ./procedures.sql/rewards.sql:/docker-entrypoint-initdb.d/09-rewards.sql
      # - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      # - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:

