  # To start:
  # docker-compose up -d
  # To stop:
  # docker-compose down
  # docker-compose exec postgres psql -U admin -d kiyoshi_db

services:
  postgres:
    image: postgres:16
    container_name: kiyoshi-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: kiyoshi_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./seed_data.sql:/docker-entrypoint-initdb.d/02-seed_data.sql
      # - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:

